Repository AgainIoT/Open-Set-Go_client, pull requests merged in 2023-10, with the labels that each got.

#94 Unexpected bugs fixed
  src/layout/Header.js
  src/pages/MainPage.js
Labels: bug

#96 Fix : manage login state only in Header #83
  src/layout/Header.js
  src/pages/MainPage.js
Labels: bug

#100 Correct old docs url
  src/layout/Header.js
Labels: bug

#115 Improve list item layout #114
  src/components/common/template/TemplateList.js
Labels: enhancement

#121 Fix everything looks wrong on step pages
  src/components/common/MarkdownPreview.js
  src/components/common/SelectAuto.js
  src/components/common/Slide.js
  src/components/common/modal/TemplateModal.js
  src/components/step1/GitignoreContainer.js
  src/components/step1/RequiredFieldContainer.js
  src/components/step1/SelectContainer.js
  src/layout/Layout.js
  src/pages/ContributingTemplatePage.js
  src/pages/CreateRepoPage.js
  src/pages/PRTemplatePage.js
  src/pages/ReadmeTemplatePage.js
Labels: bug, enhancement

#199 Fix : fix some bug in issue step
  src/components/common/IssueChip.js
  src/components/common/IssueList.js
  src/components/common/modal/IssueModal.js
Labels: bug
